### PR TITLE
Python 

### PR DESCRIPTION
**Pull request by Daksheshapkare**
## Describe your changes
Code on simple calculator 
## Issue ticket number and link - If Any
Basic python program #34 
https://github.com/MrKrishnaAgarwal/Hacktoberfest2022/issues/34
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.
Basic python program 2
```

nums=int(input("first number:"))
sign=input("sign:")
num=int(input("second number:"))
sum=0
for char in sign:
 if char == "+":
  nu=nums+num
 elif char == "/":
  nu=nums/num
 elif char == "%":
  nu=nums%num
 elif char == "-":
  nu=nums-num
 elif char == "*":
  nu=nums*num
 elif char == "**":
  nu=nums**num
 elif char == "//":
  nu=nums//num   
print(nu)

```

### CODE REVIEW

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
Again, the same issue. Please commit your code to the code files.

**Comment by Daksheshapkare** [comment]
> Again, the same issue. Please commit your code to the code files.

Can u just guide me as I am a new user in github

**Comment by MrKrishnaAgarwal** [comment]
**You all have to make your contributions from Oct 1, if you make now It will not count.**

Please read the website notices and guidelines

**Comment by Daksheshapkare** [comment]
Please check it now 
If not then I'll make new pr

**Comment by MrKrishnaAgarwal** [comment]
Make a new pr

**Pull request closed without merging**
