### PR TITLE
Odd and Even.py

### PR DESCRIPTION
**Pull request by Daksheshapkare**
## Describe your changes
I have created a py program that works upon just finding whether the no. Is even or odd
Here is the code
Number = int(input("Enter a number :-"))
if (Number %2==0 ) :
      print("This number is even")
else:
    print("This number is odd")

## Issue ticket number and link - If Any
Basic python program #34 
https://github.com/MrKrishnaAgarwal/Hacktoberfest2022/issues/34
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.
Python basic program 1 
Number = int(input("Enter a number :-"))
if (Number %2==0 ) :
      print("This number is even")
else:
    print("This number is odd")

I am sending you four python basic program
So merge that pr too and then tick and my assignment

### CODE REVIEW

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
I can't find any code changes.

**Comment by devarshishimpi** [comment]
Kindly add your code in the code files and not in the comment of your PR

**Comment by Daksheshapkare** [comment]
> I can't find any code changes.

Please tell me what changes you want.
I have done some change do check it

**Comment by MrKrishnaAgarwal** [comment]
**You all have to make your contributions from Oct 1, if you make now It will not count.**

Please read the website notices and guidelines

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
You haven't added any code
Sorry we can't merge

**Comment by MrKrishnaAgarwal** [comment]
@Daksheshapkare The contributions can be made only from Oct 1 else they will not count, and I have added the code this time in the file please add the code in the files and then Mae the pull request, for now I am approving it but remember your contribution will not count

**Review by MrKrishnaAgarwal — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
LGTM

**Review by devarshishimpi — COMMENTED** [review]
LGTM

**Comment by devarshishimpi** [comment]
> @devarshishimpi You can review this PR now and approve it if you see it's fine

And done. Looks already merged so can only review it, as not option to approve.

**Comment by MrKrishnaAgarwal** [comment]
> 
> And done. Looks already merged so can only review it, as not option to approve.

Yes 👍🏻

**Pull request merged**
