### PR TITLE
feat: added js code - renanlmiranda

### PR DESCRIPTION
**Pull request by renanlmiranda**
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
**You all have to make your contributions from Oct 1, if you make now It will not count.**

Please read the website notices and guidelines

**Comment by MrKrishnaAgarwal** [comment]
LGTM

**Comment by MrKrishnaAgarwal** [comment]
But as I said your contribution will not be counted in your total of Hacktoberfest, as it was said to make the PR only after Oct 1

**Comment by MrKrishnaAgarwal** [comment]
@all-contributors please add @renanlmiranda for code

**Comment by MrKrishnaAgarwal** [comment]
@all-contributors please add @renanlmiranda for code

**Comment by renanlmiranda** [comment]
No problem, i can do after! Thanks @MrKrishnaAgarwal

**Pull request merged**
