### PR TITLE
Issue #39 Height of Binary Tree Algorithm

### PR DESCRIPTION
**Pull request by PrakashGatiyala**
Signed-off-by: Prakash <gatiyalap@gmail.com>

## Describe your changes
Java code for Height of Binary Tree Algorithm.
## Screenshots - If Any (Optional)
image

## Issue ticket number and link - If Any
#39  
## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Starred the repository.
- [X] Added My Name to the Contributor's List.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.
Done
## Additional Information (Optional)
NA

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]
LGTM!

It looks good to me but Code factor  check failed, it's fine
If you want to fix the check you can

**Review by devarshishimpi — APPROVED** [review]
Works Fine!! Thanks For Contributing!!

**Comment by devarshishimpi** [comment]
> LGTM!
> 
> It looks good to me but Code factor check failed, it's fine If you want to fix the check you can

True

**Comment by MrKrishnaAgarwal** [comment]
This issue references #39 
Thanks

**Pull request merged**
