### PR TITLE
Added new C++ code which find height of a binary tree

### PR DESCRIPTION
**Pull request by sceary-expert**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
Looks good!

**Comment by sceary-expert** [comment]
Can you review this PR?

**Review by MrKrishnaAgarwal — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
@all-contributors please add @sceary-expert for code

**Comment by MrKrishnaAgarwal** [comment]
Done!

**Pull request merged**
