### PR TITLE
Basic drawing in Python with Turtle

### PR DESCRIPTION
**Pull request by GitSatishGarg**
## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
But as I said your contribution will not be counted in your total of Hacktoberfest, as it was said to make the PR only after Oct 1

**Comment by MrKrishnaAgarwal** [comment]
LGTM

**Comment by GitSatishGarg** [comment]
Awww, I didn't properly read it :(, anyway then after October 1, can I just make changes to code?

**Comment by MrKrishnaAgarwal** [comment]
> Awww, I didn't properly read it :(, anyway then after October 1, can I just make changes to code?

Yes sure and you can make more contributions

No worries

Thanks for contributing 🎉

**Comment by MrKrishnaAgarwal** [comment]
@all-contributors please add @GitSatishGarg for code

**Pull request merged**
