### PR TITLE
Sum of two number in Python.py

### PR DESCRIPTION
**Pull request by Daksheshapkare**
Program that adds two number

## Describe your changes
`Number1= int(input("Enter 1st your number =")) 
Number2=  int(input("Enter 2nd your number =")) 
Add = Number1 + Number2`

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by Daksheshapkare — COMMENTED** [review]
I just created a program in python
Add two number

**Comment by Daksheshapkare** [comment]
Actually I don't know what are you talking about.
Just guide me and tell me what are the steps to change it

**Comment by MrKrishnaAgarwal** [comment]
But this contribution will not count in Hacktoberfest 2022, are you fine with that.

Because I said to make contributions only after **Oct 1**.

Please inform me

Thank you
Krishna Agarwal

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
If you want your contribution to count, please make the PR after **Oct 1**

If you want me to merge now, I'll do that

Please inform me

**Comment by MrKrishnaAgarwal** [comment]
**Note: No reply in 24hrs results to close PR**

**Review by MrKrishnaAgarwal — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
**I've merged your PR but as I said your contribution will not be counted in your total of Hacktoberfest, as your PR was created before Oct 1**

## Thank-you for contributing 🎉

_Cheers_

**Comment by MrKrishnaAgarwal** [comment]
**I've merged your PR but as I said your contribution will not be counted in your total of Hacktoberfest, as your PR was created before Oct 1**

## Thank-you for contributing 🎉

_Cheers_

**But you will be added to our Contributors list for contributing successfully **

**Comment by MrKrishnaAgarwal** [comment]
@all-contributors please add @Daksheshapkare for code

**Comment by Daksheshapkare** [comment]
> If you want your contribution to count, please make the PR after **Oct 1**
> 
> If you want me to merge now, I'll do that
> 
> Please inform me

Yeah i want to merge it now 
As I am a new user in github and just want to notice some new changes 
But I want help from you
Please can you guide about any github problems i face and the common errors made by the participants and important points in hacktoberfest

**Comment by Daksheshapkare** [comment]
Hey 
I want some help from you 
1) help me in some github problems
2) common issues in hacktoberfest
3) important points in hacktoberfest

**Comment by MrKrishnaAgarwal** [comment]
How can I hep you?

**Comment by MrKrishnaAgarwal** [comment]
> Hey I want some help from you
> 
> 1. help me in some github problems
> 2. common issues in hacktoberfest
> 3. important points in hacktoberfest

What problems are you facing?

**Comment by MrKrishnaAgarwal** [comment]
Please tell me, I am ready to help you @Daksheshapkare

**Comment by Daksheshapkare** [comment]
I just want some tips about the points that I mentioned

**Comment by MrKrishnaAgarwal** [comment]
> I just want some tips about the points that I mentioned 

Okay, please wait
I'll share in a moment

**Comment by Daksheshapkare** [comment]
> > I just want some tips about the points that I mentioned 
> 
> Okay, please wait
> I'll share in a moment 

Waiting for your valueable tips

**Comment by MrKrishnaAgarwal** [comment]
@Daksheshapkare 

https://opensource.creativecommons.org/contributing-code
https://codingsight.com/git-branching-naming-convention-best-practices/

**Comment by MrKrishnaAgarwal** [comment]
Checkout these links

**Comment by Daksheshapkare** [comment]
> @Daksheshapkare 
> 
> https://opensource.creativecommons.org/contributing-code
> https://codingsight.com/git-branching-naming-convention-best-practices/

Thank you

**Comment by MrKrishnaAgarwal** [comment]
> > @Daksheshapkare

Welcome!

**Pull request merged**
